### ISSUE TITLE
スクリーンショット実行ができない

### ISSUE THREAD

**Issue by KazuSh1geru** [KazuSh1geru/desktop-screenshoter#25]
事実
- 環境によってエラー内容違う

解釈
- 単一のライブラリの干渉ではない説
- おそらくライブラリの依存関係が解決できてない。

解決策
- poetry導入する
  - 依存を解決できるようにする
- Pythonのバージョンを12系にアップデートする
- ライブラリを最新にする.

**Comment by Shungo-Matsueda** [comment]
発生したエラー
`No module named 'dotenv'`
対応策1
`pip install -r requirements.txt` の実行
対応策1 結果
`ModuleNotFoundError: No module named 'distutils'`が発生

**Comment by Shungo-Matsueda** [comment]
暫定対応

1. Python 3.11.4を自環境にインストール
2. プロジェクトディレクトリで`pyenv local 3.11.4` を実行
3. `make setup` を実行
(以下毎回行う)
4. `source .venv/bin/activate` で仮想環境に遷移
5. `python src/main.py`の実行
